[package]
name = "ckb-test-chain-utils"
version = "0.38.2"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "TODO(doc): @chuijiaolianying crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = {path = "../types", version = "= 0.38.2"}
ckb-db = { path = "../../db", version = "= 0.38.2" }
ckb-store = { path = "../../store", version = "= 0.38.2" }
ckb-chain-spec = { path = "../../spec", version = "= 0.38.2" }
ckb-dao-utils = { path = "../dao/utils", version = "= 0.38.2" }
ckb-traits = { path = "../../traits", version = "= 0.38.2" }
ckb-error = { path = "../../error", version = "= 0.38.2" }
lazy_static = "1.3.0"
faketime = "0.2.0"
ckb-resource = { path = "../../resource", version = "= 0.38.2" }
