[package]
name = "ckb-notify"
version = "0.37.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-logger = { path = "../util/logger", version = "= 0.37.1" }
ckb-app-config  = { path = "../util/app-config", version = "= 0.37.1" }
ckb-types = { path = "../util/types", version = "= 0.37.1" }
ckb-channel = { path = "../util/channel", version = "= 0.37.1" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.37.1" }

[dev-dependencies]
