[package]
name = "ckb-metrics"
version = "0.101.2-testnet1"
license = "MIT"
authors = ["Nervos <dev@nervos.org>"]
edition = "2018"
description = "A lightweight metrics facade used in CKB."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
opentelemetry = { version = "0.15", default-features=false, features = ["metrics"] }
