[package]
name = "ckb-fixed-hash"
version = "0.36.1"
license = "MIT"
authors = ["Nervos <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-fixed-hash-core = { path = "core" }
ckb-fixed-hash-macros = { path = "macros" }
