[package]
name = "ckb-rpc"
version = "0.110.3-rc1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "CKB RPC server."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-chain-spec = { path = "../spec", version = "= 0.110.3-rc1" }
ckb-types = { path = "../util/types", version = "= 0.110.3-rc1" }
ckb-network = { path = "../network", version = "= 0.110.3-rc1" }
ckb-notify = { path = "../notify", version = "= 0.110.3-rc1" }
ckb-shared = { path = "../shared", version = "= 0.110.3-rc1" }
ckb-store = { path = "../store", version = "= 0.110.3-rc1" }
ckb-sync = { path = "../sync", version = "= 0.110.3-rc1" }
ckb-chain = { path = "../chain", version = "= 0.110.3-rc1" }
ckb-logger = { path = "../util/logger", version = "= 0.110.3-rc1"}
ckb-logger-service = { path = "../util/logger-service", version = "= 0.110.3-rc1"}
ckb-network-alert = { path = "../util/network-alert", version = "= 0.110.3-rc1" }
ckb-app-config = { path = "../util/app-config", version = "= 0.110.3-rc1" }
ckb-constant = { path = "../util/constant", version = "= 0.110.3-rc1" }
jsonrpc-core = "18.0"
jsonrpc-derive = "18.0"
jsonrpc-http-server = "18.0"
jsonrpc-tcp-server = "18.0"
jsonrpc-ws-server = "18.0"
jsonrpc-server-utils = "18.0"
jsonrpc-pubsub = "18.0"
serde_json = "1.0"
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.110.3-rc1" }
ckb-verification = { path = "../verification", version = "= 0.110.3-rc1" }
ckb-verification-traits = { path = "../verification/traits", version = "= 0.110.3-rc1" }
ckb-traits = { path = "../traits", version = "= 0.110.3-rc1" }
ckb-util = { path = "../util", version = "= 0.110.3-rc1" }
ckb-systemtime = { path = "../util/systemtime", version = "= 0.110.3-rc1" }
ckb-dao = { path = "../util/dao", version = "= 0.110.3-rc1" }
ckb-error = { path = "../error", version = "= 0.110.3-rc1" }
ckb-reward-calculator = { path = "../util/reward-calculator", version = "= 0.110.3-rc1" }
ckb-tx-pool = { path = "../tx-pool", version = "= 0.110.3-rc1" }
ckb-memory-tracker = { path = "../util/memory-tracker", version = "= 0.110.3-rc1" }
ckb-pow = { path = "../pow", version = "= 0.110.3-rc1" }
ckb-indexer = { path = "../util/indexer", version = "= 0.110.3-rc1" }
itertools.workspace = true
tokio = "1"

[dev-dependencies]
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
ckb-launcher = { path = "../util/launcher", version = "= 0.110.3-rc1" }
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.110.3-rc1" }
tempfile.workspace = true
pretty_assertions = "1.3.0"
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.110.3-rc1" }
