[package]
name = "ckb-rpc"
version = "0.38.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @doitian crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-chain-spec = { path = "../spec", version = "= 0.38.2" }
ckb-types = { path = "../util/types", version = "= 0.38.2" }
ckb-network = { path = "../network", version = "= 0.38.2" }
ckb-notify = { path = "../notify", version = "= 0.38.2" }
ckb-indexer = { path = "../indexer", version = "= 0.38.2" }
ckb-shared = { path = "../shared", version = "= 0.38.2" }
ckb-store = { path = "../store", version = "= 0.38.2" }
ckb-sync = { path = "../sync", version = "= 0.38.2" }
ckb-chain = { path = "../chain", version = "= 0.38.2" }
ckb-logger = { path = "../util/logger", version = "= 0.38.2"}
ckb-channel = { path = "../util/channel", version = "= 0.38.2" }
ckb-logger-service = { path = "../util/logger-service", version = "= 0.38.2"}
ckb-network-alert = { path = "../util/network-alert", version = "= 0.38.2" }
ckb-fee-estimator = { path = "../util/fee-estimator", version = "= 0.38.2" }
ckb-app-config = { path = "../util/app-config", version = "= 0.38.2" }
jsonrpc-core = "~14.1"
jsonrpc-derive = "14.0" # quote requirement conflict
jsonrpc-http-server = "~14.1"
jsonrpc-tcp-server = "~14.1"
jsonrpc-ws-server = "~14.1"
jsonrpc-server-utils = "~14.1"
jsonrpc-pubsub = "~14.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
num_cpus = "1.10"
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.38.2" }
ckb-verification = { path = "../verification", version = "= 0.38.2" }
ckb-traits = { path = "../traits", version = "= 0.38.2" }
ckb-util = { path = "../util", version = "= 0.38.2" }
faketime = "0.2.0"
ckb-dao = { path = "../util/dao", version = "= 0.38.2" }
futures = "0.1"
ckb-error = { path = "../error", version = "= 0.38.2" }
ckb-reward-calculator = { path = "../util/reward-calculator", version = "= 0.38.2" }
ckb-tx-pool = { path = "../tx-pool", version = "= 0.38.2" }
ckb-script = { path = "../script", version = "= 0.38.2" }
ckb-memory-tracker = { path = "../util/memory-tracker", version = "= 0.38.2" }
failure = "0.1.5"

[dev-dependencies]
reqwest = "0.9.16"
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.38.2" }
tempfile = "3.0"
pretty_assertions = "0.6.1"
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.38.2" }
