[package]
name = "ckb-tx-pool"
version = "0.101.0-rc1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "The CKB tx-pool"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.101.0-rc1" }
ckb-logger = {path = "../util/logger", version = "= 0.101.0-rc1"}
ckb-verification = { path = "../verification", version = "= 0.101.0-rc1" }
faketime = "0.2"
lru = "0.6.0"
ckb-dao = { path = "../util/dao", version = "= 0.101.0-rc1" }
ckb-reward-calculator = { path = "../util/reward-calculator", version = "= 0.101.0-rc1" }
ckb-store = { path = "../store", version = "= 0.101.0-rc1" }
ckb-util = { path = "../util", version = "= 0.101.0-rc1" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.101.0-rc1" }
ckb-chain-spec = { path = "../spec", version = "= 0.101.0-rc1" }
ckb-snapshot = { path = "../util/snapshot", version = "= 0.101.0-rc1" }
ckb-error = { path = "../error", version = "= 0.101.0-rc1" }
tokio = { version = "1", features = ["sync"] }
ckb-async-runtime = { path = "../util/runtime", version = "= 0.101.0-rc1" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.101.0-rc1" }
ckb-app-config = { path = "../util/app-config", version = "= 0.101.0-rc1" }
ckb-network = { path = "../network", version = "= 0.101.0-rc1" }
ckb-channel = { path = "../util/channel", version = "= 0.101.0-rc1" }
ckb-traits = { path = "../traits", version = "= 0.101.0-rc1" }
ckb-db = { path = "../db", version = "= 0.101.0-rc1" }
sentry = { version = "0.23.0", optional = true }
serde_json = "1.0"
rand = "0.8.4"

[dev-dependencies]
tempfile = "3.0"
ckb-hash = { path = "../util/hash", version = "= 0.101.0-rc1" }

[features]
default = []
internal = []
with_sentry = ["sentry"]
