[package]
name = "ckb-tx-pool"
version = "0.38.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @zhangsoledad crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.38.2" }
ckb-logger = {path = "../util/logger", version = "= 0.38.2"}
ckb-verification = { path = "../verification", version = "= 0.38.2" }
failure = "0.1.5"
faketime = "0.2"
lru = "0.6.0"
ckb-dao = { path = "../util/dao", version = "= 0.38.2" }
ckb-reward-calculator = { path = "../util/reward-calculator", version = "= 0.38.2" }
ckb-store = { path = "../store", version = "= 0.38.2" }
ckb-util = { path = "../util", version = "= 0.38.2" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.38.2" }
ckb-chain-spec = { path = "../spec", version = "= 0.38.2" }
ckb-snapshot = { path = "../util/snapshot", version = "= 0.38.2" }
ckb-error = { path = "../error", version = "= 0.38.2" }
tokio = { version = "0.2", features = ["sync", "blocking", "rt-threaded", "macros"] }
ckb-async-runtime = { path = "../util/runtime", version = "= 0.38.2" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.38.2" }
ckb-fee-estimator = { path = "../util/fee-estimator", version = "= 0.38.2" }
ckb-app-config = { path = "../util/app-config", version = "= 0.38.2" }
ckb-notify = { path = "../notify", version = "= 0.38.2" }
