[package]
name = "ckb-store"
version = "0.37.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.37.1" }
ckb-db = { path = "../db", version = "= 0.37.1" }
ckb-chain-spec = { path = "../spec", version = "= 0.37.1" }
lru = "0.6.0"
ckb-traits = { path = "../traits", version = "= 0.37.1" }
ckb-util = { path = "../util", version = "= 0.37.1" }
ckb-error = { path = "../error", version = "= 0.37.1" }
ckb-app-config = { path = "../util/app-config", version = "= 0.37.1" }
