[package]
name = "ckb-network"
version = "0.101.2-testnet1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "ckb network implementation"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
ckb-util = { path = "../util", version = "= 0.101.2-testnet1" }
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.101.2-testnet1" }
ckb-logger = { path = "../util/logger", version = "= 0.101.2-testnet1" }
ckb-app-config = { path = "../util/app-config", version = "= 0.101.2-testnet1" }
tokio = { version = "1", features = ["sync", "macros"] }
tokio-util = { version = "0.6", features = ["codec"] }
futures = "0.3"
p2p = { version="0.4.0-alpha.2", package="tentacle", features = ["upnp", "parking_lot"] }
faketime = "0.2.0"
lazy_static = { version = "1.3.0", optional = true }
bs58 = { version = "0.3.0", optional = true }
sentry = { version = "0.23.0", optional = true }
faster-hex = { version = "0.6", optional = true }
ckb-hash = {path = "../util/hash", version = "= 0.101.2-testnet1"}
secp256k1 = {version = "0.19", features = ["recovery"], optional = true }
trust-dns-resolver = { version = "0.20", optional = true }
snap = "1"
ckb-types = { path = "../util/types", version = "= 0.101.2-testnet1" }
ipnetwork = "0.14"
serde_json = "1.0"
bloom-filters = "0.1"
ckb-spawn = { path = "../util/spawn", version = "= 0.101.2-testnet1" }

[features]
with_sentry = ["sentry"]
with_dns_seeding = ["lazy_static", "bs58", "faster-hex", "trust-dns-resolver", "secp256k1"]

[dev-dependencies]
tempfile = "3.0"
criterion = "0.3"
proptest = "1.0"
num_cpus = "1.10"
once_cell = "1.8.0"

[[bench]]
name = "peer_store"
harness = false
path = "src/benches/peer_store.rs"
