[package]
name = "ckb-miner"
version = "0.101.2-testnet1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @quake crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-logger = { path = "../util/logger", version = "= 0.101.2-testnet1" }
ckb-app-config = { path = "../util/app-config", version = "= 0.101.2-testnet1" }
ckb-types = { path = "../util/types", version = "= 0.101.2-testnet1" }
ckb-channel = { path = "../util/channel", version = "= 0.101.2-testnet1" }
ckb-hash = { path = "../util/hash", version = "= 0.101.2-testnet1" }
ckb-pow = { path = "../pow", version = "= 0.101.2-testnet1" }
rand = "0.7"
rand_distr = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.101.2-testnet1" }
hyper = { version = "0.14", features = ["http1"] }
hyper-tls = "0.5"
futures = "0.3"
lru = "0.6.0"
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.101.2-testnet1" }
ckb-async-runtime = { path = "../util/runtime", version = "= 0.101.2-testnet1" }
indicatif = "0.16"
console = "0.13.0"
eaglesong = "0.1"
base64 = "0.13.0"
jsonrpc-core = "18.0"
tokio = { version = "1", features = ["sync"]  }
