[package]
name = "ckb-miner"
version = "0.38.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @quake crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-logger = { path = "../util/logger", version = "= 0.38.2" }
ckb-app-config = { path = "../util/app-config", version = "= 0.38.2" }
ckb-types = { path = "../util/types", version = "= 0.38.2" }
ckb-channel = { path = "../util/channel", version = "= 0.38.2" }
ckb-hash = { path = "../util/hash", version = "= 0.38.2" }
ckb-pow = { path = "../pow", version = "= 0.38.2" }
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.38.2" }
hyper = "0.12"
hyper-tls = "0.3"
futures = "0.1"
lru = "0.6.0"
ckb-stop-handler = { path = "../util/stop-handler", version = "= 0.38.2" }
failure = "0.1.5"
indicatif = "0.15"
console = "0.13.0"
eaglesong = "0.1"
