[package]
name = "ckb-util"
version = "0.35.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
parking_lot = "=0.7.1"
linked-hash-map = "0.5"

[dev-dependencies]
ckb-fixed-hash = { path = "fixed-hash" }


[features]
deadlock_detection = ["parking_lot/deadlock_detection"]
