[package]
name = "ckb-wasm-test"
version = "0.37.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.37.1" }
ckb-script = { path = "../script", version = "= 0.37.1", default-features = false, features = [] }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]
