[package]
name = "ckb-chain-spec"
version = "0.37.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
ckb-types = { path = "../util/types", version = "= 0.37.1" }
ckb-pow = { path = "../pow", version = "= 0.37.1" }
ckb-resource = { path = "../resource", version = "= 0.37.1" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.37.1" }
ckb-dao-utils = { path = "../util/dao/utils", version = "= 0.37.1" }
ckb-rational = { path = "../util/rational", version = "= 0.37.1" }
ckb-crypto = { path = "../util/crypto", version = "= 0.37.1"}
ckb-hash = { path = "../util/hash", version = "= 0.37.1"}
failure = "0.1.5"
ckb-error = { path = "../error", version = "= 0.37.1" }
