[package]
name = "ckb-dao-utils"
version = "0.35.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
ckb-types = { path = "../../types" }
ckb-error = { path = "../../../error" }
failure = "0.1.5"
enum-display-derive = "0.1.0"
