[package]
name = "ckb-bin"
version = "0.38.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @doitian crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
clap = { version = "2" }
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3.0"
toml = "0.5"
ckb-app-config = { path = "../util/app-config", version = "= 0.38.2" }
ckb-logger = { path = "../util/logger", version = "= 0.38.2" }
ckb-logger-service = { path = "../util/logger-service", version = "= 0.38.2" }
ckb-metrics-service = { path = "../util/metrics-service", version = "= 0.38.2" }
ckb-util = { path = "../util", version = "= 0.38.2" }
ckb-types = { path = "../util/types", version = "= 0.38.2" }
ckb-channel = { path = "../util/channel", version = "= 0.38.2" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.38.2" }
ckb-chain = { path = "../chain", version = "= 0.38.2" }
ckb-shared = { path = "../shared", version = "= 0.38.2" }
ckb-store = { path = "../store", version = "= 0.38.2" }
ckb-chain-spec = {path = "../spec", version = "= 0.38.2"}
ckb-miner = { path = "../miner", version = "= 0.38.2" }
ckb-network = { path = "../network", version = "= 0.38.2"}
ckb-rpc = { path = "../rpc", version = "= 0.38.2"}
ckb-resource = { path = "../resource", version = "= 0.38.2"}
ckb-network-alert = { path = "../util/network-alert", version = "= 0.38.2" }
ctrlc = { version = "3.1", features = ["termination"] }
ckb-sync = { path = "../sync", version = "= 0.38.2"}
ckb-instrument = { path = "../util/instrument", version = "= 0.38.2", features = ["progress_bar"] }
ckb-build-info = { path = "../util/build-info", version = "= 0.38.2" }
ckb-memory-tracker = { path = "../util/memory-tracker", version = "= 0.38.2" }
ckb-chain-iter = { path = "../util/chain-iter", version = "= 0.38.2" }
ckb-verification = { path = "../verification", version = "= 0.38.2" }
base64 = "0.10.1"
tempfile = "3.0"
rayon = "1.0"
sentry = "0.17.0"

[features]
deadlock_detection = ["ckb-util/deadlock_detection"]
profiling = ["ckb-memory-tracker/profiling"]
