[package]
name = "ckb-script"
version = "0.37.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
build = "build.rs"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[features]
default = ["logging", "asm"]

asm = ["ckb-vm/asm"]
detect-asm = ["ckb-vm/detect-asm"]
logging = ["ckb-logger"]

[dependencies]
ckb-traits = { path = "../traits", version = "= 0.37.1" }
byteorder = "1.3.1"
ckb-types = {path = "../util/types", version = "= 0.37.1"}
ckb-hash = {path = "../util/hash", version = "= 0.37.1"}
ckb-vm = { version = "0.19.2", default-features = false }
faster-hex = "0.4"
ckb-logger = { path = "../util/logger", version = "= 0.37.1", optional = true }
serde = { version = "1.0", features = ["derive"] }
ckb-error = { path = "../error", version = "= 0.37.1" }
failure = "0.1.5"
ckb-chain-spec = { path = "../spec", version = "= 0.37.1" }
goblin = "0.2"
ckb-vm-definitions = "0.19.1"

[dev-dependencies]
proptest = "0.9"
ckb-db = { path = "../db", version = "= 0.37.1" }
ckb-store = { path = "../store", version = "= 0.37.1" }
ckb-test-chain-utils = { path = "../util/test-chain-utils", version = "= 0.37.1" }
tiny-keccak = "1.4"
ckb-crypto = { path = "../util/crypto", version = "= 0.37.1"}
