[package]
name = "ckb-shared"
version = "0.37.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.37.1" }
ckb-chain-spec = { path = "../spec", version = "= 0.37.1" }
ckb-store = { path = "../store", version = "= 0.37.1" }
ckb-db = { path = "../db", version = "= 0.37.1" }
ckb-proposal-table = { path = "../util/proposal-table", version = "= 0.37.1" }
arc-swap = "0.4"
ckb-error = { path = "../error", version = "= 0.37.1" }
ckb-snapshot = { path = "../util/snapshot", version = "= 0.37.1" }
ckb-tx-pool = { path = "../tx-pool", version = "= 0.37.1" }
ckb-verification = { path = "../verification", version = "= 0.37.1" }
ckb-notify = { path = "../notify", version = "= 0.37.1" }
ckb-app-config = { path = "../util/app-config", version = "= 0.37.1" }
ckb-db-migration = { path = "../db-migration", version = "= 0.37.1" }
num_cpus = "1.10"
