[package]
name = "ckb-multisig"
version = "0.37.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-logger = { path = "../logger", version = "= 0.37.1" }
ckb-crypto = { path = "../crypto", version = "= 0.37.1" }
failure = "0.1.5"

[dev-dependencies]
rand = "0.6.5"
