[package]
name = "ckb-app-config"
version = "0.104.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
license = "MIT"
description = "CKB command line arguments and config options."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
clap = { version = "3.1.5" }
serde = { version = "1.0", features = ["derive"] }
serde_plain = "0.3.0"
serde_json = "1.0"
toml = "0.5"
path-clean = "0.1.0"
ckb-logger = { path = "../../util/logger", version = "= 0.104.1" }
ckb-logger-config = { path = "../../util/logger-config", version = "= 0.104.1" }
ckb-metrics-config = { path = "../../util/metrics-config", version = "= 0.104.1" }
ckb-chain-spec = {path = "../../spec", version = "= 0.104.1"}
ckb-jsonrpc-types = {path = "../jsonrpc-types", version = "= 0.104.1"}
ckb-pow = { path = "../../pow", version = "= 0.104.1" }
ckb-resource = { path = "../../resource", version = "= 0.104.1"}
ckb-build-info = { path = "../build-info", version = "= 0.104.1" }
ckb-types = { path = "../types", version = "= 0.104.1" }
secio = { version="0.5.0", package="tentacle-secio" }
multiaddr = { version="0.3.0", package="tentacle-multiaddr" }
rand = "0.7"
sentry = { version = "0.26.0", optional = true }
faketime = "0.2.0"
url = { version = "2.2.2", features = ["serde"] }
ubyte = { version = "0.10", features = ["serde"] }

[features]
with_sentry = ["sentry"]

[dev-dependencies]
tempfile = "3.0"
