[package]
name = "ckb-db-migration"
version = "0.38.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @quake crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-db = { path = "../db", version = "= 0.38.2" }
ckb-logger = { path = "../util/logger", version = "= 0.38.2" }
ckb-error = { path = "../error", version = "= 0.38.2" }
indicatif = "0.15"
console = "0.13"

[dev-dependencies]
tempfile = "3.0"
ckb-app-config = { path = "../util/app-config", version = "= 0.38.2" }
