[package]
name = "ckb-types"
version = "0.37.1"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "TODO(doc): crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
molecule = "=0.6.0"
ckb-fixed-hash = { path = "../fixed-hash", version = "= 0.37.1" }
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
bytes = { version="0.5.4", features = ["serde"] }
merkle-cbt = "0.3"
ckb-occupied-capacity = { path = "../occupied-capacity", version = "= 0.37.1" }
ckb-hash = { path = "../hash", version = "= 0.37.1" }
ckb-channel = { path = "../channel", version = "= 0.37.1" }
bit-vec = "0.5.1"
failure = "0.1.5"
ckb-error = { path = "../../error", version = "= 0.37.1" }
ckb-rational = { path = "../rational", version = "= 0.37.1" }
once_cell = "1.3.1"

[dev-dependencies]
proptest = "0.9"
