[package]
name = "ckb-network-alert"
version = "0.38.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "TODO(doc): @driftluo crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-multisig = { path = "../multisig", version = "= 0.38.2" }
ckb-types = { path = "../types", version = "= 0.38.2" }
ckb-util = { path = "..", version = "= 0.38.2" }
ckb-network = { path = "../../network", version = "= 0.38.2" }
ckb-notify = { path = "../../notify", version = "= 0.38.2"}
ckb-jsonrpc-types = { path = "../jsonrpc-types", version = "= 0.38.2" }
ckb-logger = { path = "../logger", version = "= 0.38.2"}
ckb-app-config = { path = "../app-config", version = "= 0.38.2" }
faketime = "0.2.0"
failure = "0.1.5"
lru = "0.6"
semver = "0.9"

[dev-dependencies]
ckb-crypto = { path = "../crypto", version = "= 0.38.2" }
