[package]
name = "ckb-network-alert"
version = "0.104.1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"
description = "The alert protocol implementation"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-multisig = { path = "../multisig", version = "= 0.104.1" }
ckb-types = { path = "../types", version = "= 0.104.1" }
ckb-util = { path = "..", version = "= 0.104.1" }
ckb-network = { path = "../../network", version = "= 0.104.1" }
ckb-notify = { path = "../../notify", version = "= 0.104.1"}
ckb-jsonrpc-types = { path = "../jsonrpc-types", version = "= 0.104.1" }
ckb-logger = { path = "../logger", version = "= 0.104.1"}
ckb-app-config = { path = "../app-config", version = "= 0.104.1" }
ckb-error = { path = "../../error", version = "= 0.104.1" }
faketime = "0.2.0"
lru = "0.7.1"
semver = "1.0"

[dev-dependencies]
ckb-crypto = { path = "../crypto", version = "= 0.104.1" }
