name: Smoking test suit

on:
  workflow_dispatch:
    inputs:
       CKB_linux_release_package:
        description: 'Linux release package to somking test'
        required: false
  repository_dispatch:
    types: [ smoking-test ]
env:
  RUSTFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  TESTNET_SNAPSHOT_URL: ${{secrets.TESTNET_SNAPSHOT_URL}}
  CARGO_TARGET_DIR: ${{ github.workspace }}/../target

jobs:
   Start_and_sync:
    runs-on: [self-hosted,Linux]
    steps:
    - uses: actions/checkout@v2
    - name: Download&Unzip v0.35.0
      run: |
        if [ ! -f "/tmp/ckb_v0.35.0_linux.tar.gz" ]; then
           curl -L https://github.com/nervosnetwork/ckb/releases/download/v0.35.0/ckb_v0.35.0_x86_64-unknown-linux-gnu.tar.gz -o /tmp/ckb_v0.35.0_linux.tar.gz
        fi
        tar -zxf /tmp/ckb_v0.35.0_linux.tar.gz -C /tmp
        cp /tmp/ckb_*/ckb ${{ github.workspace }}/ckb
    - name: Update ExecStart&StandardOutput
      run: |
          sed -i  "s#ExecStart=.*#ExecStart=${{github.workspace}}/ckb run -C ${{github.workspace}}#g" ${{ github.workspace }}/devtools/smoking_test/ckb.service
          sed -i  "s#StandardOutput=.*#StandardOutput=file:${{github.workspace}}/data/logs/run.log#g" ${{ github.workspace }}/devtools/smoking_test/ckb.service
    - name: Init&Start ckb testnet with v0.35.0
      run: |
        ${{ github.workspace }}/ckb init -c testnet -C ${{ github.workspace }} --force
        sudo cp ${{ github.workspace }}/devtools/smoking_test/ckb.service /etc/systemd/system/ckb.service
        sudo systemctl daemon-reload
        sudo systemctl enable ckb
        sudo service ckb start
        sleep 600
        sudo service ckb stop
        sudo systemctl disable ckb
        sudo rm /etc/systemd/system/ckb.service
        sudo systemctl daemon-reload
        sudo systemctl reset-failed
        rm ${{ github.workspace }}/ckb
    - name: Download target ckb release pkg and copy binary to github workspace
      if: |
        (github.event_name == 'workflow_dispatch' && github.event.inputs.CKB_linux_release_package != '')
        || contains(github.event_name, 'repository_dispatch')
      run: |
        if [ -z ${{ github.event.inputs.CKB_linux_release_package }} ]; then
        curl -L ${{ github.event.client_payload.CKB_linux_release_package }} -o /tmp/ckb.7z
        7za x "/tmp/ckb.7z" -r -o/tmp
        fi
        if [ -z ${{ github.event.client_payload.CKB_linux_release_package }} ]; then
        curl -L ${{ github.event.inputs.CKB_linux_release_package }} -o /tmp/ckb.tar.gz
        tar -zxf /tmp/ckb.tar.gz -C /tmp
        fi
    - name: Build CKB binary
      if: |
       (github.event_name == 'workflow_dispatch' && github.event.inputs.CKB_linux_release_package == '')
       && ! contains(github.event_name, 'repository_dispatch')
      run: |
        make build
        cp ${CARGO_TARGET_DIR}/release/ckb ${{ github.workspace }}/ckb
    - name: Update ExecStart&StandardOutput
      run: |
          sed -i  "s#ExecStart=.*#ExecStart=${{github.workspace}}/ckb run -C ${{github.workspace}}#g" ${{ github.workspace }}/devtools/smoking_test/ckb.service
          sed -i  "s#StandardOutput=.*#StandardOutput=file:${{github.workspace}}/data/logs/run.log#g" ${{ github.workspace }}/devtools/smoking_test/ckb.service
    - name: Regenerate testnet configuration
      run: |
        ${{ github.workspace }}/ckb init -c testnet -C ${{ github.workspace }} --force
    - name: Migration check
      run: |
        ${{ github.workspace }}/devtools/smoking_test/check-migrate.sh
    - name: Start ckb service.
      if: ${{ success() }}
      run: |
            sudo cp ${{ github.workspace }}/devtools/smoking_test/ckb.service /etc/systemd/system/ckb.service
            sudo systemctl daemon-reload
            sudo systemctl enable ckb
            sudo service ckb start
            sudo service ckb status
    - name: Ensure the ckb service is health.
      run: ${{ github.workspace }}/devtools/smoking_test/tip_block_growth_check.sh
    - name: Stop & clean ckb service.
      if: ${{ success() }}
      run: |
         rm -rf /tmp/data
         rm -rf /tmp/ckb_*
         sudo service ckb stop
         sudo systemctl disable ckb
         sudo systemctl daemon-reload
         sudo systemctl reset-failed
         sudo rm /etc/systemd/system/ckb.service
    env:
      CKB_DIR: ${{ github.workspace }}
